// useEncryptionHandler.ts (React Browser Version)
import CryptoJS from "crypto-js";
import useCompression from "./useCompression";

export const MASTER_KEY = "metamux-secret-workspace-salt-key";

// Match the exact hashing and IV slicing your Node/Bun code used
const hash = CryptoJS.SHA256(MASTER_KEY);
const KRYPTO_KEY = hash;
// Slice the first 16 bytes (4 words in CryptoJS terms) for the IV
const KRYPTO_IV = CryptoJS.lib.WordArray.create(hash.words.slice(0, 4));

const useEncryptionHandler = () => {
	const { pack, unpack } = useCompression();

	// This will now perfectly decrypt tokens generated by your Bun CLI tool!
	const readToken = (token: string): string => {
		try {
			// Convert the incoming hex token string into cipher bytes
			const cipherParams = CryptoJS.lib.CipherParams.create({
				ciphertext: CryptoJS.enc.Hex.parse(token),
			});

			const decrypted = CryptoJS.AES.decrypt(cipherParams, KRYPTO_KEY, {
				iv: KRYPTO_IV,
				mode: CryptoJS.mode.CBC,
				padding: CryptoJS.pad.Pkcs7,
			});
			console.log(unpack(decrypted.toString(CryptoJS.enc.Utf8)));
			return unpack(decrypted.toString(CryptoJS.enc.Utf8));
		} catch (error) {
			console.error("Decryption failed:", error);
			throw new Error("Invalid token payload");
		}
	};

	const createToken = (text: string): string => {
		const encrypted = CryptoJS.AES.encrypt(pack(text) as string, KRYPTO_KEY, {
			iv: KRYPTO_IV,
			mode: CryptoJS.mode.CBC,
			padding: CryptoJS.pad.Pkcs7,
		});
		return encrypted.ciphertext.toString(CryptoJS.enc.Hex);
	};

	return {
		createToken,
		readToken,
	};
};

export default useEncryptionHandler;
